server:
  port: 8080
  servlet:
    session:
      timeout: 86400
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://43.138.69.76:3306/yp
  application:
    name: yp-backend

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

